services:
  api:
    env_file:
      - "app/.env"
    build:
      context: .
      dockerfile: Dockerfile
      #args:
    image: poptape/address/api:v0.1
    ports:
      - "1238:8011"
    restart: always
    volumes:
      - ${LOCAL_LOG_LOC}:/addresses/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - poptape
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1239:5432"
    volumes:
      - poptape_address_data:/var/lib/postgresql/data
    networks:
      - poptape
networks:
  poptape:
    external: true
volumes:
  poptape_address_data:
  
